### ISSUE TITLE
训练loss相关问题

### ISSUE THREAD

**Issue by Ar4enal** [paradiseDust/ChineseFoodNet-EffiNet-L2#1]
我这边使用了train.py的默认参数开始训练，但是显示的loss一直没什么变化，使用某些epoch保存的模型预测准确率也不高。

请问您训练时候遇到过吗，有没有要改的地方

![image](https://user-images.githubusercontent.com/36718239/179649235-8e343f31-449e-4f38-8ba3-db5e7bddea72.png)

**Comment by Ar4enal** [comment]
已解决，要修改一些参数 -_-

**Comment by LiujiChen** [comment]
抱歉，我刚刚看到邮件，解决了就好，可能是我上传的时候选择了test_demo，没有选择最后的参数，因为我调试的时候是在笔记本上调试的，我把很多超参重新设置了，为了能够run起来，实际的最佳超参你可以参考原论文，如果可以的话，你可以将你的issue放入仓库，避免后面有需要的人也遇到这个问题，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paradiseDust/ChineseFoodNet-EffiNet-L2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 下午2:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [paradiseDust/ChineseFoodNet-EffiNet-L2] 训练loss相关问题 (Issue #1)





 
已解决，要修改一些参数 -_-

**Comment by Ar4enal** [comment]
```
label_smoothing  0.01
learning rate    0.01
threads          4
weight_decay     0.0001
```

改了这些，供参考
